version: '3.8'

services:
  api:
    tty: True
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb://db/myTestDB
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - taskdb:/data/db
  frontend:
      build: ./frontend
      ports:
        - "8080:80"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy-data:/data
        - caddy-config:/config
      depends_on:
        - api


volumes:
    taskdb:
    caddy-data:
    caddy-config: